### ISSUE TITLE
ssh密钥连接

### ISSUE THREAD

**Issue by etins** [jiangxianli/SSHAutoLogin#4]
如果是ssh密钥连接，怎么处理啊？

以下是我根据楼主的代码改写的支持密钥连接，做了一些微小的改动
https://gist.github.com/etins/4286cda07d5afa6899cbd9cb7ec60270

**Comment by Jack-data-dev** [comment]
同求支持秘钥对连接

**Comment by jiangxianli** [comment]
@yinmazhong 已增加秘钥方式连接，同时也感谢 @etins 的支持

**Comment by rainplus** [comment]
mac 用户 进行$转义\\\$后，也无法登录。。提示密码错误，没有$的其他转义成功登录！
