### ISSUE TITLE
字符.需要转译吗，“b.11111111”无法登录成功

### ISSUE THREAD

**Issue by iwwz** [jiangxianli/SSHAutoLogin#6]
字符.需要转译吗，“b.11111111”无法登录成功

**Comment by jiangxianli** [comment]
@iwwz 需要的，需要转义成"b\\.11111111"

**Comment by iwwz** [comment]
emmmmm....引号是我手加的，密码中符号只有那个点

**Comment by jiangxianli** [comment]
@iwwz 我知道，.需要转义成\\.

**Comment by jiangxianli** [comment]
#默认服务器配置项
#    "服务器名称 端口号 IP地址 登录用户名 登录密码"
CONFIGS=(
    "Ubuntu 22 192.168.11.194 root b\.111111"
)

我配置文件这样配置，可以连上的。

**Comment by jiangxianli** [comment]
@iwwz 

#默认服务器配置项
#"服务器名称 端口号 IP地址 登录用户名 登录密码"
CONFIGS=(
    "Ubuntu 22 192.168.11.194 root b\\.111111"
)
我配置文件这样配置是可以连上的。

**Comment by jiangxianli** [comment]
@iwwz markdown自动把我写的\\.转义了,你看下我上面的这个例子

**Comment by iwwz** [comment]
@jiangxianli 谢谢！
