### ISSUE TITLE
Mac下不能适应屏幕

### ISSUE THREAD

**Issue by ZizhenWang** [jiangxianli/SSHAutoLogin#9]
我把mac命令行全屏之后，使用这个脚本访问的服务器并没有一起全屏，还是原始大小显示的

**Comment by mowangjuanzi** [comment]
这个是mac的情况。我在终端中经常碰到。

**Comment by ZizhenWang** [comment]
@jizhidemowang 有什么解决办法吗

**Comment by mowangjuanzi** [comment]
没有啊，习惯了就好了。你可以尝试使用iterm2试试看。
